<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pokemon extends \App\Entity\Pokemon implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Atk' => [parent::class, 'Atk', null, 16],
        "\0".parent::class."\0".'Def' => [parent::class, 'Def', null, 16],
        "\0".parent::class."\0".'Hp' => [parent::class, 'Hp', null, 16],
        "\0".parent::class."\0".'SpAtk' => [parent::class, 'SpAtk', null, 16],
        "\0".parent::class."\0".'SpDef' => [parent::class, 'SpDef', null, 16],
        "\0".parent::class."\0".'Spd' => [parent::class, 'Spd', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'locamons' => [parent::class, 'locamons', null, 16],
        "\0".parent::class."\0".'sprites' => [parent::class, 'sprites', null, 16],
        "\0".parent::class."\0".'translations' => [parent::class, 'translations', null, 16],
        "\0".parent::class."\0".'type1' => [parent::class, 'type1', null, 16],
        "\0".parent::class."\0".'type2' => [parent::class, 'type2', null, 16],
        'Atk' => [parent::class, 'Atk', null, 16],
        'Def' => [parent::class, 'Def', null, 16],
        'Hp' => [parent::class, 'Hp', null, 16],
        'SpAtk' => [parent::class, 'SpAtk', null, 16],
        'SpDef' => [parent::class, 'SpDef', null, 16],
        'Spd' => [parent::class, 'Spd', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'locamons' => [parent::class, 'locamons', null, 16],
        'sprites' => [parent::class, 'sprites', null, 16],
        'translations' => [parent::class, 'translations', null, 16],
        'type1' => [parent::class, 'type1', null, 16],
        'type2' => [parent::class, 'type2', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
