<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Type extends \App\Entity\Type implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'color' => [parent::class, 'color', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'name_en' => [parent::class, 'name_en', null, 16],
        "\0".parent::class."\0".'name_fr' => [parent::class, 'name_fr', null, 16],
        "\0".parent::class."\0".'pokemonsType1' => [parent::class, 'pokemonsType1', null, 16],
        "\0".parent::class."\0".'pokemonsType2' => [parent::class, 'pokemonsType2', null, 16],
        "\0".parent::class."\0".'sprite' => [parent::class, 'sprite', null, 16],
        'color' => [parent::class, 'color', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'name_en' => [parent::class, 'name_en', null, 16],
        'name_fr' => [parent::class, 'name_fr', null, 16],
        'pokemonsType1' => [parent::class, 'pokemonsType1', null, 16],
        'pokemonsType2' => [parent::class, 'pokemonsType2', null, 16],
        'sprite' => [parent::class, 'sprite', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
