<?php

namespace ContainerD5s6V37;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IVbU_YTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IVbU.yT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IVbU.yT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LocamonController::index' => ['privates', '.service_locator.73Qjsm7.App\\Controller\\LocamonController::index()', 'getLocamonControllerindexService', true],
            'App\\Controller\\LocamonController::new' => ['privates', '.service_locator.TCbS7EP.App\\Controller\\LocamonController::new()', 'getLocamonControllernewService', true],
            'App\\Controller\\LocamonController::show' => ['privates', '.service_locator.1czhfrB.App\\Controller\\LocamonController::show()', 'getLocamonControllershowService', true],
            'App\\Controller\\LocamonController::edit' => ['privates', '.service_locator.QcfG1fn.App\\Controller\\LocamonController::edit()', 'getLocamonControllereditService', true],
            'App\\Controller\\LocamonController::delete' => ['privates', '.service_locator.QcfG1fn.App\\Controller\\LocamonController::delete()', 'getLocamonControllerdeleteService', true],
            'App\\Controller\\PokemonsController::index' => ['privates', '.service_locator.sbroXCa.App\\Controller\\PokemonsController::index()', 'getPokemonsControllerindexService', true],
            'App\\Controller\\PokemonsController::show' => ['privates', '.service_locator._WRd.Th.App\\Controller\\PokemonsController::show()', 'getPokemonsControllershowService', true],
            'App\\Controller\\ShopController::index' => ['privates', '.service_locator.73Qjsm7.App\\Controller\\ShopController::index()', 'getShopControllerindexService', true],
            'App\\Controller\\ShopController::show' => ['privates', '.service_locator.1czhfrB.App\\Controller\\ShopController::show()', 'getShopControllershowService', true],
            'App\\Controller\\ShopController::checkout' => ['privates', '.service_locator.1czhfrB.App\\Controller\\ShopController::checkout()', 'getShopControllercheckoutService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.4ievYoR.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LocamonController:index' => ['privates', '.service_locator.73Qjsm7.App\\Controller\\LocamonController::index()', 'getLocamonControllerindexService', true],
            'App\\Controller\\LocamonController:new' => ['privates', '.service_locator.TCbS7EP.App\\Controller\\LocamonController::new()', 'getLocamonControllernewService', true],
            'App\\Controller\\LocamonController:show' => ['privates', '.service_locator.1czhfrB.App\\Controller\\LocamonController::show()', 'getLocamonControllershowService', true],
            'App\\Controller\\LocamonController:edit' => ['privates', '.service_locator.QcfG1fn.App\\Controller\\LocamonController::edit()', 'getLocamonControllereditService', true],
            'App\\Controller\\LocamonController:delete' => ['privates', '.service_locator.QcfG1fn.App\\Controller\\LocamonController::delete()', 'getLocamonControllerdeleteService', true],
            'App\\Controller\\PokemonsController:index' => ['privates', '.service_locator.sbroXCa.App\\Controller\\PokemonsController::index()', 'getPokemonsControllerindexService', true],
            'App\\Controller\\PokemonsController:show' => ['privates', '.service_locator._WRd.Th.App\\Controller\\PokemonsController::show()', 'getPokemonsControllershowService', true],
            'App\\Controller\\ShopController:index' => ['privates', '.service_locator.73Qjsm7.App\\Controller\\ShopController::index()', 'getShopControllerindexService', true],
            'App\\Controller\\ShopController:show' => ['privates', '.service_locator.1czhfrB.App\\Controller\\ShopController::show()', 'getShopControllershowService', true],
            'App\\Controller\\ShopController:checkout' => ['privates', '.service_locator.1czhfrB.App\\Controller\\ShopController::checkout()', 'getShopControllercheckoutService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.4ievYoR.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LocamonController::index' => '?',
            'App\\Controller\\LocamonController::new' => '?',
            'App\\Controller\\LocamonController::show' => '?',
            'App\\Controller\\LocamonController::edit' => '?',
            'App\\Controller\\LocamonController::delete' => '?',
            'App\\Controller\\PokemonsController::index' => '?',
            'App\\Controller\\PokemonsController::show' => '?',
            'App\\Controller\\ShopController::index' => '?',
            'App\\Controller\\ShopController::show' => '?',
            'App\\Controller\\ShopController::checkout' => '?',
            'App\\Controller\\UserController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LocamonController:index' => '?',
            'App\\Controller\\LocamonController:new' => '?',
            'App\\Controller\\LocamonController:show' => '?',
            'App\\Controller\\LocamonController:edit' => '?',
            'App\\Controller\\LocamonController:delete' => '?',
            'App\\Controller\\PokemonsController:index' => '?',
            'App\\Controller\\PokemonsController:show' => '?',
            'App\\Controller\\ShopController:index' => '?',
            'App\\Controller\\ShopController:show' => '?',
            'App\\Controller\\ShopController:checkout' => '?',
            'App\\Controller\\UserController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
        ]);
    }
}
