<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QcfG1fnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QcfG1fn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QcfG1fn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'locamon' => ['privates', '.errored..service_locator.QcfG1fn.App\\Entity\\Locamon', NULL, 'Cannot autowire service ".service_locator.QcfG1fn": it needs an instance of "App\\Entity\\Locamon" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'locamon' => 'App\\Entity\\Locamon',
            'em' => '?',
        ]);
    }
}
