<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocamonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1czhfrB.App\Entity\Locamon' shared service.
     *
     * @return \App\Entity\Locamon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1czhfrB": it needs an instance of "App\\Entity\\Locamon" but this type has been excluded in "config/services.yaml".');
    }
}
