<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocamonControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.73Qjsm7.App\Controller\LocamonController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.73Qjsm7'] ?? $container->load('get_ServiceLocator_73Qjsm7Service'));

        if (isset($container->privates['.service_locator.73Qjsm7.App\\Controller\\LocamonController::index()'])) {
            return $container->privates['.service_locator.73Qjsm7.App\\Controller\\LocamonController::index()'];
        }

        return $container->privates['.service_locator.73Qjsm7.App\\Controller\\LocamonController::index()'] = $a->withContext('App\\Controller\\LocamonController::index()', $container);
    }
}
