<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavbarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Navbar' autowired service.
     *
     * @return \App\Twig\Components\Navbar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'Navbar.php';

        $container->factories['service_container']['App\\Twig\\Components\\Navbar'] = function ($container) {
            return new \App\Twig\Components\Navbar();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Navbar']($container);
    }
}
