<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._WRd.Th.App\Controller\PokemonsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._WRd.Th.App\\Controller\\PokemonsController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokemon' => ['privates', '.errored..service_locator._WRd.Th.App\\Entity\\Pokemon', NULL, 'Cannot autowire service ".service_locator._WRd.Th": it needs an instance of "App\\Entity\\Pokemon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pokemon' => 'App\\Entity\\Pokemon',
        ]))->withContext('App\\Controller\\PokemonsController::show()', $container);
    }
}
