<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._WRd.Th.App\Entity\Pokemon' shared service.
     *
     * @return \App\Entity\Pokemon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._WRd.Th": it needs an instance of "App\\Entity\\Pokemon" but this type has been excluded in "config/services.yaml".');
    }
}
