<?php

namespace ContainerRj3GHZT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopControllercheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1czhfrB.App\Controller\ShopController::checkout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1czhfrB.App\\Controller\\ShopController::checkout()'] = ($container->privates['.service_locator.1czhfrB'] ?? $container->load('get_ServiceLocator_1czhfrBService'))->withContext('App\\Controller\\ShopController::checkout()', $container);
    }
}
