<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOfiuFTQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOfiuFTQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOfiuFTQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOfiuFTQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOfiuFTQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OfiuFTQ',
    'container.build_id' => '4e2b3784',
    'container.build_time' => 1781593768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOfiuFTQ');
