<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRj3GHZT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRj3GHZT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRj3GHZT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRj3GHZT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRj3GHZT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rj3GHZT',
    'container.build_id' => '9cf4839c',
    'container.build_time' => 1764133138,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRj3GHZT');
